export default {
  at: "2022-04-02T21:05:21.742Z",
  products: [
    {
      description: "duis in aute et",
      name: "mollit",
      price: 1914.49,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "id officia adipisicing qui",
      name: "minim",
      price: 1588.48,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "tempor sit deserunt consequat",
      name: "labore",
      price: 378.99,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "tempor sunt ullamco sint",
      name: "sit",
      price: 1858.76,
      tmpProperty: undefined,
      activePromoId: 57,
    },
    {
      description: "nulla excepteur nostrud reprehenderit",
      name: "veniam",
      price: 1823.31,
      tmpProperty: undefined,
      activePromoId: 30,
    },
    {
      description: "nostrud amet consectetur aliqua",
      name: "magna",
      price: 584.42,
      tmpProperty: undefined,
      activePromoId: 95,
    },
    {
      description: "occaecat enim officia nisi",
      name: "aliquip",
      price: 825.38,
      tmpProperty: undefined,
      activePromoId: 44,
    },
    {
      description: "ex aliqua dolore duis",
      name: "cupidatat",
      price: 1082.06,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "exercitation reprehenderit dolore reprehenderit",
      name: "labore",
      price: 1540.86,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {
      description: "ullamco mollit commodo enim",
      name: "mollit",
      price: 1774.69,
      tmpProperty: undefined,
      activePromoId: 38,
    },
    {
      description: "proident amet do commodo",
      name: "ea",
      price: 1209.64,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "laboris nisi nisi amet",
      name: "veniam",
      price: 1138.11,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "elit anim mollit aliquip",
      name: "enim",
      price: 443.74,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "amet magna adipisicing laboris",
      name: "incididunt",
      price: 780.42,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "exercitation velit duis aute",
      name: "proident",
      price: 1798.16,
      tmpProperty: undefined,
      activePromoId: 42,
    },
    {
      description: "nulla eiusmod nulla pariatur",
      name: "aliqua",
      price: 309.33,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ea ipsum exercitation voluptate",
      name: "et",
      price: 1585.29,
      tmpProperty: undefined,
      activePromoId: 27,
    },
    {
      description: "eu ullamco incididunt anim",
      name: "elit",
      price: 101.24,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sit ipsum velit id",
      name: "do",
      price: 1388.29,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sint mollit mollit ea",
      name: "est",
      price: 1784.42,
      tmpProperty: undefined,
      activePromoId: 99,
    },
    {
      description: "deserunt consequat magna aute",
      name: "irure",
      price: 561.8,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cupidatat proident anim tempor",
      name: "anim",
      price: 332.19,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "veniam officia minim laboris",
      name: "elit",
      price: 938.79,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "labore quis veniam nisi",
      name: "esse",
      price: 949.19,
      tmpProperty: undefined,
      activePromoId: 58,
    },
    {
      description: "consequat laboris qui adipisicing",
      name: "minim",
      price: 248.06,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "voluptate ullamco sit aliquip",
      name: "non",
      price: 1792.09,
      tmpProperty: undefined,
      activePromoId: 39,
    },
    {
      description: "dolore minim non esse",
      name: "id",
      price: 1009.59,
      tmpProperty: undefined,
      activePromoId: 11,
    },
    {
      description: "ipsum deserunt in ut",
      name: "sunt",
      price: 179.25,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nulla aliquip amet labore",
      name: "duis",
      price: 1225.52,
      tmpProperty: undefined,
      activePromoId: 23,
    },
    {
      description: "ullamco do nostrud excepteur",
      name: "occaecat",
      price: 969.47,
      tmpProperty: undefined,
      activePromoId: 6,
    },
    {
      description: "dolor ea qui exercitation",
      name: "cillum",
      price: 1282.69,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sunt id est labore",
      name: "aliqua",
      price: 1804.51,
      tmpProperty: undefined,
      activePromoId: 98,
    },
    {
      description: "nulla qui qui eu",
      name: "enim",
      price: 1139.59,
      tmpProperty: undefined,
      activePromoId: 41,
    },
    {
      description: "velit officia eu eu",
      name: "deserunt",
      price: 863.16,
      tmpProperty: undefined,
      activePromoId: 53,
    },
    {
      description: "incididunt duis sit pariatur",
      name: "esse",
      price: 1592.53,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nisi irure aute velit",
      name: "do",
      price: 922.15,
      tmpProperty: undefined,
      activePromoId: 70,
    },
    {
      description: "enim et aliquip ullamco",
      name: "laboris",
      price: 1660.09,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "Lorem dolor eu ex",
      name: "laborum",
      price: 818.57,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sint veniam in aute",
      name: "consectetur",
      price: 665.21,
      tmpProperty: undefined,
      activePromoId: 57,
    },
    {
      description: "mollit officia eu adipisicing",
      name: "eu",
      price: 589.33,
      tmpProperty: undefined,
      activePromoId: 8,
    },
    {
      description: "do adipisicing aliqua laboris",
      name: "qui",
      price: 715.62,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eiusmod ut nostrud nostrud",
      name: "cillum",
      price: 1277.64,
      tmpProperty: undefined,
      activePromoId: 85,
    },
    {
      description: "magna esse mollit eu",
      name: "magna",
      price: 212.46,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "culpa duis adipisicing aliqua",
      name: "exercitation",
      price: 694.77,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "voluptate duis dolore laboris",
      name: "mollit",
      price: 478.34,
      tmpProperty: undefined,
      activePromoId: 48,
    },
    {
      description: "dolore Lorem labore sint",
      name: "esse",
      price: 1926.41,
      tmpProperty: undefined,
      activePromoId: 98,
    },
    {
      description: "tempor velit fugiat nisi",
      name: "sint",
      price: 690.78,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "quis amet laboris reprehenderit",
      name: "occaecat",
      price: 665.78,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "esse occaecat officia consectetur",
      name: "duis",
      price: 1652.04,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "duis Lorem sint cillum",
      name: "eu",
      price: 1834.04,
      tmpProperty: undefined,
      activePromoId: 53,
    },
    {
      description: "irure consectetur ea sint",
      name: "laboris",
      price: 753.03,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "exercitation non magna commodo",
      name: "do",
      price: 780.8,
      tmpProperty: undefined,
      activePromoId: 15,
    },
    {
      description: "pariatur duis pariatur labore",
      name: "Lorem",
      price: 667.01,
      tmpProperty: undefined,
      activePromoId: 54,
    },
    {
      description: "minim officia ea eu",
      name: "occaecat",
      price: 524.07,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "id ut tempor laboris",
      name: "aliqua",
      price: 1975.5,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "qui nisi duis aliquip",
      name: "officia",
      price: 1613.15,
      tmpProperty: undefined,
      activePromoId: 25,
    },
    {
      description: "nulla deserunt sunt excepteur",
      name: "enim",
      price: 1667.21,
      tmpProperty: undefined,
      activePromoId: 66,
    },
    {
      description: "dolore eiusmod dolor ipsum",
      name: "culpa",
      price: 1865.07,
      tmpProperty: undefined,
      activePromoId: 14,
    },
    {
      description: "fugiat qui amet reprehenderit",
      name: "qui",
      price: 1175.08,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nisi cillum sint nulla",
      name: "exercitation",
      price: 1954.01,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "voluptate culpa adipisicing quis",
      name: "esse",
      price: 763.09,
      tmpProperty: undefined,
      activePromoId: 85,
    },
    {
      description: "aute deserunt ut nostrud",
      name: "in",
      price: 118.35,
      tmpProperty: undefined,
      activePromoId: 77,
    },
    {
      description: "et veniam deserunt fugiat",
      name: "irure",
      price: 1995.6,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "quis excepteur aute tempor",
      name: "reprehenderit",
      price: 928.93,
      tmpProperty: undefined,
      activePromoId: 30,
    },
    {
      description: "cupidatat veniam id ipsum",
      name: "ad",
      price: 1240.4,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "minim cillum adipisicing ad",
      name: "sint",
      price: 1266.75,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "magna irure Lorem ut",
      name: "nostrud",
      price: 1852.63,
      tmpProperty: undefined,
      activePromoId: 5,
    },
    {
      description: "do incididunt aute elit",
      name: "reprehenderit",
      price: 1030.88,
      tmpProperty: undefined,
      activePromoId: 79,
    },
    {
      description: "ad sunt aliquip culpa",
      name: "consequat",
      price: 132.29,
      tmpProperty: undefined,
      activePromoId: 94,
    },
    {
      description: "occaecat enim duis est",
      name: "aliquip",
      price: 863.1,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "quis sunt ad cupidatat",
      name: "elit",
      price: 1152.69,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "officia veniam pariatur irure",
      name: "pariatur",
      price: 524.62,
      tmpProperty: undefined,
      activePromoId: 89,
    },
    {
      description: "sunt cillum in occaecat",
      name: "laboris",
      price: 1673.24,
      tmpProperty: undefined,
      activePromoId: 30,
    },
    {
      description: "aliqua enim quis irure",
      name: "sit",
      price: 1134.19,
      tmpProperty: undefined,
      activePromoId: 99,
    },
    {
      description: "proident culpa fugiat occaecat",
      name: "esse",
      price: 275.2,
      tmpProperty: undefined,
      activePromoId: 55,
    },
    {
      description: "ullamco sunt elit laboris",
      name: "id",
      price: 1189.97,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ea laboris nostrud est",
      name: "culpa",
      price: 166.06,
      tmpProperty: undefined,
      activePromoId: 13,
    },
    {
      description: "et in labore sunt",
      name: "pariatur",
      price: 1148.78,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ut eu tempor nulla",
      name: "exercitation",
      price: 1240.64,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aute aute ipsum ullamco",
      name: "aute",
      price: 825.51,
      tmpProperty: undefined,
      activePromoId: 46,
    },
    {
      description: "sunt exercitation deserunt labore",
      name: "duis",
      price: 1819.24,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "consequat labore nulla aliquip",
      name: "cupidatat",
      price: 1528.25,
      tmpProperty: undefined,
      activePromoId: 56,
    },
    {
      description: "do ipsum eu pariatur",
      name: "dolor",
      price: 469.66,
      tmpProperty: undefined,
      activePromoId: 84,
    },
    {
      description: "fugiat quis sint id",
      name: "nisi",
      price: 950.94,
      tmpProperty: undefined,
      activePromoId: 13,
    },
    {
      description: "occaecat incididunt esse mollit",
      name: "duis",
      price: 1452.75,
      tmpProperty: undefined,
      activePromoId: 26,
    },
    {
      description: "anim excepteur est incididunt",
      name: "amet",
      price: 548.76,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "duis esse ullamco cupidatat",
      name: "qui",
      price: 817.34,
      tmpProperty: undefined,
      activePromoId: 68,
    },
    {
      description: "eu laboris nulla adipisicing",
      name: "ut",
      price: 627.29,
      tmpProperty: undefined,
      activePromoId: 0,
    },
    {
      description: "elit aute ad excepteur",
      name: "ut",
      price: 1729.24,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "irure exercitation adipisicing exercitation",
      name: "Lorem",
      price: 1819.66,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "fugiat fugiat excepteur eu",
      name: "nulla",
      price: 754.98,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ullamco cillum in mollit",
      name: "enim",
      price: 1622.75,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "irure sint magna sunt",
      name: "non",
      price: 932.38,
      tmpProperty: undefined,
      activePromoId: 93,
    },
    {
      description: "est cupidatat adipisicing ex",
      name: "nulla",
      price: 481.37,
      tmpProperty: undefined,
      activePromoId: 42,
    },
    {
      description: "consequat voluptate officia deserunt",
      name: "consequat",
      price: 674.81,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "tempor irure aute ipsum",
      name: "fugiat",
      price: 311.56,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "reprehenderit ex sunt id",
      name: "minim",
      price: 672.91,
      tmpProperty: undefined,
      activePromoId: 1,
    },
    {
      description: "elit excepteur officia aliqua",
      name: "aliqua",
      price: 436.58,
      tmpProperty: undefined,
      activePromoId: 28,
    },
    {
      description: "consectetur minim sint anim",
      name: "et",
      price: 1405.35,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: "quis laborum nisi minim",
      name: "nulla",
      price: 1199.74,
      tmpProperty: undefined,
      activePromoId: null,
    },
  ],
};
